# Generated by Django 3.2.13 on 2022-06-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220624_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='Share your opinion!', max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Share your story!', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='Tell us a little bit about your post!', max_length=100),
        ),
    ]
