# Generated by Django 3.2.13 on 2022-06-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220629_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Share your story!', max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='Tell us a little bit about your post!', max_length=500),
        ),
    ]
