# Generated by Django 3.2.13 on 2022-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220630_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('font_awesome_class', models.CharField(blank=True, max_length=50, null=True)),
                ('base_url', models.CharField(blank=True, default='https://instagram.com/ or https://tiktok.com/@', max_length=50, null=True)),
            ],
        ),
    ]
